import type { Metadata } from "next";
import { Anton, Blaka_Hollow } from "next/font/google";
import "./globals.css";

const AntonFont = Anton({
  weight: "400",
  variable: "--font-anton",

  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Port",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${AntonFont.className} antialiased`}>{children}</body>
    </html>
  );
}
